# Generated by Django 2.2.1 on 2019-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('team1', models.CharField(max_length=128)),
                ('team2', models.CharField(max_length=128)),
                ('toss_winner', models.CharField(max_length=128)),
                ('toss_decision', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
                ('dl_applied', models.BooleanField()),
                ('winner', models.CharField(max_length=128)),
                ('winner_by_runs', models.IntegerField()),
                ('winner_by_wickets', models.IntegerField()),
                ('player_of_the_match', models.CharField(max_length=128)),
                ('venue', models.CharField(max_length=128)),
                ('umpire1', models.CharField(max_length=128)),
                ('umpire2', models.CharField(max_length=128)),
                ('umpire3', models.CharField(max_length=128)),
            ],
        ),
    ]
