# Generated by Django 2.2.1 on 2019-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0004_auto_20190617_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='batsman',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='batting_team',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowler',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='bowling_team',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='dismissal_kind',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='fielder',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='non_striker',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_dismissed',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
