# Generated by Django 2.2.1 on 2019-06-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0005_auto_20190617_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='match',
        ),
    ]
